baseURL = 'https://giacomocavalieri.github.io/master-thesis-slides/'
languageCode = 'it'
title = 'Gestione Esplicita degli Effetti'
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

[author]
name = "Giacomo Cavalieri"

[params.reveal_hugo]
theme = "white"
custom_theme = "custom-theme.scss"
custom_theme_compile = true
slide_number = false
pdfSeparateFragments = false
highlight_theme = "github-gist"
width = "1440"
height = "900"

[markup.goldmark.renderer]
unsafe = true

[params.reveal_hugo.custom_theme_options]
targetPath = "css/custom-theme.css"
enableSourceMap = true

[markup.highlight]
noClasses = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[[params.reveal_hugo.mermaid]]
startOnLoad = false
theme = "default"
fontFamily = "Inconsolata"
useMaxWidth = false